apiVersion: v1
kind: Namespace
metadata:
  name: securepay-prod
  labels:
    name: securepay-prod
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: securepay-staging
  labels:
    name: securepay-staging
    environment: staging
